"""Grafana HTTP API client — push dashboards via POST /api/dashboards/db."""

import os

import httpx

GRAFANA_URL = os.getenv("GRAFANA_URL", "http://grafana:3000").rstrip("/")
GRAFANA_ADMIN_USER = os.getenv("GRAFANA_ADMIN_USER", "admin")
GRAFANA_ADMIN_PASSWORD = os.getenv("GRAFANA_ADMIN_PASSWORD", "code9-demo-admin")


async def health_check() -> bool:
    """Return True if Grafana responds with HTTP 200 on /api/health."""
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            r = await client.get(
                f"{GRAFANA_URL}/api/health",
                auth=(GRAFANA_ADMIN_USER, GRAFANA_ADMIN_PASSWORD),
            )
            return r.status_code == 200
    except Exception:
        return False


async def upsert_dashboard(dashboard_json: dict) -> dict:
    """Push a dashboard to Grafana (create or overwrite by UID).

    Args:
        dashboard_json: The Grafana dashboard object (must include ``uid``).

    Returns:
        The Grafana API response dict, e.g. ``{"uid": "...", "url": "..."}``.

    Raises:
        httpx.HTTPStatusError: on 4xx/5xx from Grafana.
    """
    payload = {
        "dashboard": dashboard_json,
        "overwrite": True,
        "message": "Auto-generated by maritime dynamic dashboard agent",
    }
    async with httpx.AsyncClient(timeout=30.0) as client:
        r = await client.post(
            f"{GRAFANA_URL}/api/dashboards/db",
            json=payload,
            auth=(GRAFANA_ADMIN_USER, GRAFANA_ADMIN_PASSWORD),
            headers={"Content-Type": "application/json"},
        )
        r.raise_for_status()
        return r.json()
